server:
  port: 8880
spring:
  application:
    name: wiki
  datasource:
    url: jdbc:mysql://rm-2zehsi4i3cj077tj1bo.mysql.rds.aliyuncs.com:3306/wikidev?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wikidev
    password: Wiki1234
  redis:
    host: r-uf6ljbcdaxobsifyctpd.redis.rds.aliyuncs.com
    port: 6379
    password: Redis000
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      java:
        wiki:
          mapper: trace
