GET http://localhost:8880/hello
Accept: application/json

###
POST http://localhost:8880/hello/post
Content-Type: application/x-www-form-urlencoded

name=TEST12

###

GET http://localhost:8880/test/list
###

GET http://localhost:8880/redis/get/103015748082995200
Accept: application/json

###